version: '2.3'

x-lagoon-project:
  &lagoon-project moodle-example 
  &cli-image $DOCKER_REPO/moodle_cli:$BUILDTAG


x-environment:
  &default-environment
    LAGOON_PROJECT: *lagoon-project
    # Route that should be used locally
    LAGOON_ROUTE: http://moodle-example.docker.amazee.io
    # Uncomment if you like to have the system behave like in production
    #LAGOON_ENVIRONMENT_TYPE: production
    # Uncomment to enable xdebug and then restart via `docker-compose up -d`
    #XDEBUG_ENABLE: "true"

services:

  cli: # cli container, used for executing composer and any local commands (artisan, etc)
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: $DOCKER_REPO/moodle_cli:$BUILDTAG # this image will be reused as `CLI_IMAGE` in subsequent Docker builds
    labels:
      lagoon.type: cli
    #volumes_from: # mount the ssh-agent from the pygmy or cachalot ssh-agent
      #- container:amazeeio-ssh-agent
    environment:
      << : *default-environment # loads the defined environment variables from the top
    depends_on:
      - mariadb 

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        CLI_IMAGE: $DOCKER_REPO/moodle_cli:$BUILDTAG  # Inject the name of the cli image
    image: $DOCKER_REPO/moodle_nginx:$BUILDTAG
    labels:
      lagoon.type: nginx-php
    depends_on:
      - cli 
    environment:
      << : *default-environment # loads the defined environment variables from the top
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      args:
        CLI_IMAGE: $DOCKER_REPO/moodle_cli:$BUILDTAG 
    image: $DOCKER_REPO/moodle_php:$BUILDTAG
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx # we want this service be part of the nginx pod in Lagoon
    depends_on:
      - cli 
    environment:
      << : *default-environment # loads the defined environment variables from the top

  mariadb:
    image: amazeeio/mariadb
    labels:
      lagoon.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis-persistent #we make this persistent because we're storing jobs, not simply caching things
    environment:
      << : *default-environment

networks:
  amazeeio-network:
    external: true
